name: streaming_shared_preferences_example
description: An example project for streaming_shared_preferences.
environment:
  sdk: '>=2.12.0 <3.0.0'
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  streaming_shared_preferences:
    path: ../

flutter:
  uses-material-design: true
